- alias: "Run At Sunset 20 minutes before the actual sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.at_sunset

# This really should also be a scene, but let's see if this works for
# now while I think of a better way to do this. :)
- alias: "Turn off the front porch at sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "00:20:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.front_porch_light

# Trigger the "Away from Home" scene when we're all gone
- alias: "Everyone leaves the house"
  trigger:
    platform: state
    entity_id: group.all_furries
    to: "not_home"
  action:
    service: homeassistant.turn_on
    entity_id: scene.away_from_home

# Dim the lights at 9pm if I'm home
- alias: "Dim lights at 9:00pm"
  initial_state: true
  trigger:
    platform: time
    at: "21:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: person.april
        state: home
  action:
    - service: scene.turn_on
      entity_id: scene.low_key

# Start up HomeKit once ZWave is ready
- alias: "Start HomeKit"
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start

#
# MQTT Events
#

# Living room
- alias: "MQTT - Living Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.living_room_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/living_room/motion"
      payload_template: "{{ states.binary_sensor.living_room_motion_sensor_motion.state }}"

- alias: "MQTT - Living Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.living_room_motion_sensor_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/living_room/temperature"
      payload_template: "{{ states.sensor.living_room_motion_sensor_temperature.state }}"

# Laundry room
- alias: "MQTT - Laundry Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.laundry_room_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/motion"
      payload_template: "{{ states.binary_sensor.laundry_room_motion.state }}"

- alias: "MQTT - Laundry Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/temperature"
      payload_template: "{{ states.sensor.laundry_room_temperature.state }}"

# Bedroom
- alias: "MQTT - Bedroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.bedroom_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/motion"
      payload_template: "{{ states.binary_sensor.bedroom_motion_sensor_motion.state }}"

- alias: "MQTT - Bedroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/temperature"
      payload_template: "{{ states.sensor.bedroom_temperature.state }}"

# Bathroom
- alias: "MQTT - Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/bathroom/motion"
      payload_template: "{{ states.binary_sensor.bathroom_motion.state }}"

- alias: "MQTT - Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/bathroom/temperature"
      payload_template: "{{ states.sensor.bathroom_temperature.state }}"
