- alias: "Run At Sunset 20 minutes before the actual sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.at_sunset

# This really should also be a scene, but let's see if this works for
# now while I think of a better way to do this. :)
- alias: "Turn off the outside lights at sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "00:20:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom_door_light

# Trigger the "Away from Home" scene when we're all gone
- alias: "Everyone leaves the house"
  trigger:
    platform: state
    entity_id: group.all_furries
    to: "not_home"
  action:
    service: homeassistant.turn_on
    entity_id: scene.away_from_home

# Dim the outside lights around bedtime
- alias: "Dim the outside lights at sleep time"
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.sleepy_time

# Dim the lights at 9pm if I'm home
- alias: "Dim lights at 9:00pm"
  initial_state: true
  trigger:
    platform: time
    at: "21:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: person.april
        state: home
  action:
    - service: scene.turn_on
      entity_id: scene.low_key

# Turn on the lights in the hallway bathroom when it's dark and motion is detected
- alias: Turn on the hallway bathroom stars with motion at night
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_bathroom_motion
    to: "on"
  condition:
    condition: numeric_state
    entity_id: sensor.hallway_bathroom_luminance
    below: 10.0
  action:
    service: light.turn_on
    entity_id: light.hallway_bathroom_stars

- alias: Turn off the hallway bathroom stars if it's night time
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_bathroom_motion
    to: "off"
    for:
      minutes: 10
  condition:
    - condition: time
      after: "21:00:00"
      before: "07:00:00"
  action:
    service: light.turn_off
    entity_id: light.hallway_bathroom_stars

# Push the value of the rain we got yesterday into a retained mqtt topic
- alias: "Push previous day rain total to MQTT"
  trigger:
    - platform: time
      at: "00:00:01"
  action:
    service: mqtt.publish
    data_template:
      topic: "internal/rain_in_prior"
      retain: true
      payload: "{{ states.sensor.rain_amount.state }}"

######################################3
#
# MQTT Events
#

# Living room
- alias: "MQTT - Living Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.living_room_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/living_room/motion"
      payload_template: "{{ states.binary_sensor.living_room_motion_sensor_motion.state }}"

- alias: "MQTT - Living Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.living_room_motion_sensor_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/living_room/temperature"
      payload_template: "{{ states.sensor.living_room_motion_sensor_temperature.state }}"

# Laundry room
- alias: "MQTT - Laundry Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.laundry_room_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/motion"
      payload_template: "{{ states.binary_sensor.laundry_room_motion.state }}"

- alias: "MQTT - Laundry Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/temperature"
      payload_template: "{{ states.sensor.laundry_room_temperature.state }}"

- alias: "MQTT - Laundry Room Room Humidity"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/humidity"
      payload_template: "{{ states.sensor.laundry_room_relative_humidity.state }}"

# Bedroom
- alias: "MQTT - Bedroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.bedroom_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/motion"
      payload_template: "{{ states.binary_sensor.bedroom_motion_sensor_motion.state }}"

- alias: "MQTT - Bedroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/temperature"
      payload_template: "{{ states.sensor.bedroom_temperature.state }}"

# Hallway Bathroom
- alias: "MQTT - Hallway Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.hallway_bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/motion"
      payload_template: "{{ states.binary_sensor.hallway_bathroom_motion.state }}"

- alias: "MQTT - Hallway Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.hallway_bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/temperature"
      payload_template: "{{ states.sensor.hallway_bathroom_temperature.state }}"

- alias: "MQTT - Hallway Bathroom Room Humidity"
  trigger:
    platform: state
    entity_id: "sensor.hallway_bathroom_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/humidity"
      payload_template: "{{ states.sensor.hallway_bathroom_relative_humidity.state }}"

# Office
- alias: "MQTT - Office Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.office_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/office/motion"
      payload_template: "{{ states.binary_sensor.office_motion_sensor_motion.state }}"

- alias: "MQTT - Office Temperature"
  trigger:
    platform: state
    entity_id: "sensor.office_motion_sensor_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/office/temperature"
      payload_template: "{{ states.sensor.office_motion_sensor_temperature.state }}"

# Kitchen
- alias: "MQTT - Kitchen Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.kitchen_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/motion"
      payload_template: "{{ states.binary_sensor.kitchen_motion.state }}"

- alias: "MQTT - Kitchen Temperature"
  trigger:
    platform: state
    entity_id: "sensor.kitchen_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/temperature"
      payload_template: "{{ states.sensor.kitchen_temperature.state }}"

- alias: "MQTT - Kitchen Humidity"
  trigger:
    platform: state
    entity_id: "sensor.kitchen_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/humidity"
      payload_template: "{{ states.sensor.kitchen_relative_humidity.state }}"

# Outside
- alias: "MQTT - Outside Temperature"
  trigger:
    platform: state
    entity_id: "sensor.outside_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/temperature"
      payload_template: "{{ states.sensor.outside_temperature.state }}"

- alias: "MQTT - Outside Humidity"
  trigger:
    platform: state
    entity_id: "sensor.outside_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/humidity"
      payload_template: "{{ states.sensor.outside_humidity.state }}"

- alias: "MQTT - Outside Wind Avgerage"
  trigger:
    platform: state
    entity_id: "sensor.wind_speed_avg"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/wind_average"
      payload_template: "{{ states.sensor.wind_speed_avg.state }}"

- alias: "MQTT - Outside Wind Bearing"
  trigger:
    platform: state
    entity_id: "sensor.wind_bearing"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/wind_bearing"
      payload_template: "{{ states.sensor.wind_bearing.state }}"

- alias: "MQTT - Outside Wind Direction"
  trigger:
    platform: state
    entity_id: "sensor.wind_direction"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/wind_direction"
      payload_template: "{{ states.sensor.wind_direction.state }}"

- alias: "MQTT - Outside Conditions"
  trigger:
    platform: state
    entity_id: "weather.april_s_nest"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/conditions"
      payload_template: "{{ states.weather.april_s_nest.state }}"

- alias: "MQTT - Outside Sun"
  trigger:
    platform: state
    entity_id: "sun.sun"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/sun"
      payload_template: "{{ states.sun.sun.state }}"

- alias: "MQTT - Outside Air Quailty"
  trigger:
    platform: state
    entity_id: "sensor.airnow_aqi"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/air_quality"
      payload_template: "{{ states.sensor.airnow_aqi.state }}"

## Things!

# Living Room Heater
- alias: "MQTT - Living Room Heater State"
  trigger:
    platform: state
    entity_id: "switch.living_room_heater"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/heater/state"
      payload_template: "{{ states.switch.living_room_heater.state }}"

- alias: "MQTT - Living Room Heater Power"
  trigger:
    platform: state
    entity_id: "sensor.living_room_heater_power"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/heater/power"
      payload_template: "{{ states.sensor.living_room_heater_power.state }}"

# Bedroom Fan
- alias: "MQTT - Bedroom Fan State"
  trigger:
    platform: state
    entity_id: "switch.bedroom_fan"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/state"
      payload_template: "{{ states.switch.bedroom_fan.state }}"

- alias: "MQTT - Bedroom Fan Power"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_fan_power"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/power"
      payload_template: "{{ states.sensor.bedroom_fan_power.state }}"

- alias: "MQTT - Everyone Home"
  trigger:
    platform: state
    entity_id: "group.all_furries"
  action:
    service: mqtt.publish
    data:
      topic: "people/furries/home"
      payload_template: "{{ states.group.all_furries.state }}"

- alias: "MQTT - Living Room TV"
  trigger:
    platform: state
    entity_id: "media_player.living_room_tv"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/tv/state"
      payload_template: "{{ states.media_player.living_room_tv.state }}"

- alias: "MQTT - Work Computer Camera"
  trigger:
    platform: state
    entity_id: "binary_sensor.april_s_work_mac_mini_camera_in_use"
  action:
    service: mqtt.publish
    data:
      topic: "thing/office/computer_camera/state"
      payload_template: "{{ states.binary_sensor.april_s_work_mac_mini_camera_in_usestate }}"

- alias: "MQTT - Work Computer Microphone"
  trigger:
    platform: state
    entity_id: "binary_sensor.april_s_work_mac_mini_microphone_in_use"
  action:
    service: mqtt.publish
    data:
      topic: "thing/office/computer_microphone/state"
      payload_template: "{{ states.binary_sensor.april_s_work_mac_mini_microphone_in_use.state }}"
