
#
# The Zooz 4-in-1 sensors use the "burglar" type to report motion, so let's
# map that to what HA expects instead.
#
# See https://www.home-assistant.io/docs/z-wave/entities#burglar-entity
#
- platform: template
  sensors:
    bathroom_motion:
      friendly_name: "Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bathroom_burglar', '8') }}"

- platform: template
  sensors:
    guest_room_motion:
      friendly_name: "Guest Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.guest_room_burglar', '8') }}"

- platform: template
  sensors:
    laundry_room_motion:
      friendly_name: "Laundry Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.laundry_room_burglar', '8') }}"


- platform: template
  sensors:
    laundry_room_motion:
      friendly_name: "Backyard Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bathroom_burglar', '3') }}"
