#
# This is a pretty basic HA config, for now at least. :)
#

default_config:

homeassistant:
  name: April's Nest
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  internal_url: !secret home_internal_url
  legacy_templates: false
  customize: !include customizations.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.3.2.5

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes/

discovery:

homekit: !include homekit.yaml

zone: !include zones.yaml

# Enable ZWave! This might be better in it's own file eventually
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_secure_key
  polling_interval: 30000
  config_path: /config/ozwave/config

# Present this Z-Wave device as a light
light:
  - platform: switch
    name: Patio Lights
    entity_id: switch.patio_lights

# MQTT Config
mqtt: !include mqtt.yaml

# Manually-defined sensors
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml

# Enable iOS stuff
ios: !include ios.yaml

# Turn on themes
frontend:
  themes: !include_dir_merge_named themes

# Talk to mpd on the localhost interface
media_player:
  - platform: mpd
    host: 127.0.0.1
