
#
# Manually defined sensors
#


### MQTT

- platform: mqtt
  name: "Second Life Concurrency"
  state_topic: "sl/concurrency"
  unit_of_measurement: 'resis'
  value_template: "{{ value_json.concurrency }}"
  json_attributes_topic: "sl/concurrency"

### End MQTT